language: go
script: 
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go tool cover -func=coverage.txt
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
